# Generated by Django 4.2.7 on 2025-11-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno'),
        ),
    ]
